tweety_mctweetface/config/routes.rb
Rails.application.routes.draw do

  root 'epicenter#feed'

  get 'show_user' => 'epicenter#show_user'

  get 'now_following' => 'epicenter#now_following'

  get 'unfollow' => 'epicenter#unfollow'

  get 'tag_tweets' => 'epicenter#tag_tweets'

  get 'all_users' => 'epicenter#all_users'

  get 'following' => 'epicenter#following'

  get 'followers' => 'epicenter#followers'

  resources :tweets
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  
end

tweety_mctweetface/app/controllers/epicenter_controller.rb
class EpicenterController < ApplicationController
  def feed
    # feed looks for a current user in the do block.  If logging out, page errors because the root path is set to epicenter#feed and no current_user exists on logout. This if statement redirects to the login screen if there is no current_user.
    if current_user != nil
      # initiate an empty array and assign it to the instance variable @following_tweets
      @following_tweets = []
      # get all the Tweets and iterate through them
      Tweet.all.each do |tweet|
        # if in the current iteration, the tweet.user_id is in the current_user's following attribute column OR if the current_user id equates to the tweet.user_id
        if (current_user.following.include?(tweet.user_id) || current_user.id == tweet.user_id)
          # add that tweet to the following_tweets array
          @following_tweets.push(tweet)
        end
      end
    else
      redirect_to new_user_session_url
    end
  end

  def all_users
    # assign all users, orderd by username, to the instance variable @users
    @users = User.order(:username)
  end

  def tag_tweets
    # assign the tag with the specified id to the instance variable @tag
    @tag = Tag.find(params[:id])
  end

  def show_user
    # assign the user with the specified id to the instance variable @user
  	@user = User.find(params[:id])
  end

  def following
    # assign the user with the specified id to the instance variable @user
    @user = User.find(params[:id])
    # initiate an empty array and assign it to the instance variable @users
    @users = []

    # get all users and iterate through them
    User.all.each do |user|
      # if the itereated user.id is included in this instance of the user's following attribute
      if @user.following.include?(user.id)
        #push this user into the @users array
        @users.push(user)
      end
    end
  end
  
  def followers
    # same as above for following
    @user = User.find(params[:id])
    @users = []

    # same as above for following
    User.all.each do |user|
      # if this instance of user.id is included in the the following column of the iterated user
      if user.following.include?(@user.id)
        # push this user into the @users array
        @users.push(user)
      end
    end
  end

  def now_following
    # push the selected user_id into the array that is in the following attribute for the current_user
  	current_user.following.push(params[:id].to_i)
    # save this updated array (current_user is given to us by Devise and follows it's own syntax)
  	current_user.save
    # do not go to the now_following view. go to the show_user view for the selected id.
  	redirect_to show_user_path(id: params[:id])
  end

  def unfollow
    # remove the selected user_id from the array that is in the following column for the current_user
  	current_user.following.delete(params[:id].to_i)
  	current_user.save

  	redirect_to show_user_path(id: params[:id])
  end
end

tweety_mctweetface/app/helpers/epicenter_helper.rb
module EpicenterHelper
end

tweety_mctweetface/app/views/epicenter/_user_list.html.erb
<div class="row">
  <% @users.each do |user| %>
    <div class="col-md-4">
      <div class="well">
        <div class="row">
          <div class="col-md-6">
            <%= image_tag user.avatar.url, size: 150, class: "img-responsive" %>
          </div>
          <div class="col-md-6">
            <br>
            <p>
              <% if current_user.id != user.id %>
                <% if current_user.following.include?(user.id) %>
                  <%= link_to "Following", unfollow_path(id: user.id), class: "btn btn-primary", id: "unfollow_btn" %>
                <% else %>
                  <%= link_to "Follow", now_following_path(id: user.id), class: "btn btn-primary" %>
                <% end %>
              <% end %>
            </p>
          </div>
        </div>
        <div class="row">
          <div>
          <%= link_to show_user_path(id: user.id) do %>
            <h3><%= user.name %></h3>
            <p>@<%= user.username %></p>
          <% end %>
          <p>
            <%= user.bio %>
          </p>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

tweety_mctweetface/app/views/epicenter/all_users.html.erb
<h3><strong>Who to Follow</strong></h3>
<%= render 'user_list' %>

tweety_mctweetface/app/views/epicenter/feed.html.erb
<h2>@<%= current_user.username %>'s Feed</h2>


<h4>Here's what your friends are saying</h4>

<div>
	<% @following_tweets.reverse.each do |tweet| %>
		<div class="well">
			<p>
				<%= image_tag tweet.user.avatar.url, size: 50, class: "img-responsive" %>
				<%= link_to tweet.user.name, show_user_path(id: tweet.user.id) %>
				<%= link_to ('@' + tweet.user.username), show_user_path(id: tweet.user_id) %>
				&bull; 
				<%= time_ago_in_words(tweet.created_at) if Time.now - tweet.created_at < 86400 %> 
				<%= tweet.created_at.strftime('%b%e') if Time.now - tweet.created_at > 86400 %> 
			</p>
			<p>
				<%= tweet.message.html_safe %>
			</p>
		</div>
	<% end %>
</div>

tweety_mctweetface/app/views/epicenter/followers.html.erb
<h2><%= @user.name %>'s Followers</h2>
<%= render 'user_list' %>

tweety_mctweetface/app/views/epicenter/following.html.erb
<h2><%= @user.name %> is following</h2>
<%= render 'user_list' %>

tweety_mctweetface/app/views/epicenter/show_user.html.erb
<h1>@<%= @user.username %>'s Profile & Tweets</h1>

<div class="well">
    <%= image_tag @user.avatar.url, size: 250, class: "img-responsive" %>
    <p><%= @user.name %></p>
    <p><%= @user.location %></p>
    <p><%= @user.bio %></p>
</div>

<p>
    <% if current_user.following.include?(@user.id) %>
        <%= link_to "Unfollow", unfollow_path(id: @user.id), class: "btn btn-primary", id: "unfollow_btn" %>
    <% else %>
        <% if current_user.id != @user.id %>
	    <%= link_to "Follow", now_following_path(id: @user.id), class: "btn btn-primary" %>
	<% end %>
    <% end %>
</p>

<ul>
    <li><%= link_to "Followers", followers_path(id: @user.id) %></li>
    <li><%= link_to "Following", following_path(id: @user.id) %></li>
</ul>

<% @user.tweets.each do |tweet| %>
    <div class="well">
        <p>@<%= @user.username %></p>
	<p><%= tweet.message.html_safe %></p>
    </div>
<% end %>

tweety_mctweetface/app/views/epicenter/tag_tweets.html.erb
<div>
    <h1><%= @tag.phrase %></h1>
</div>

<div class="row">
  <!-- a place for current user stats -->
  <div>
    <% @tag.tweets.order(created_at: :desc).each do |tweet| %>
    <div class="well">
        <p> 
          <%= image_tag tweet.user.avatar, width: 50, class: "img_responsive"%>
    	    <%= tweet.user.name %> <%= "@#{tweet.user.username}" %>
    	    • <%= time_ago_in_words(tweet.created_at) %>
        </p>

      	<p>
      	    <%= tweet.message.html_safe %>
      	</p>
    </div>
    <% end %>
   </div>
</div>